// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"erajaya-test/internal/models/entity"
	"erajaya-test/internal/models/request"

	mock "github.com/stretchr/testify/mock"
)

// NewProductRepository creates a new instance of ProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductRepository {
	mock := &ProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProductRepository is an autogenerated mock type for the ProductRepository type
type ProductRepository struct {
	mock.Mock
}

type ProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductRepository) EXPECT() *ProductRepository_Expecter {
	return &ProductRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ProductRepository
func (_mock *ProductRepository) Create(ctx context.Context, product *entity.Product) error {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Product) error); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ProductRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - product *entity.Product
func (_e *ProductRepository_Expecter) Create(ctx interface{}, product interface{}) *ProductRepository_Create_Call {
	return &ProductRepository_Create_Call{Call: _e.mock.On("Create", ctx, product)}
}

func (_c *ProductRepository_Create_Call) Run(run func(ctx context.Context, product *entity.Product)) *ProductRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Product
		if args[1] != nil {
			arg1 = args[1].(*entity.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductRepository_Create_Call) Return(err error) *ProductRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductRepository_Create_Call) RunAndReturn(run func(ctx context.Context, product *entity.Product) error) *ProductRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function for the type ProductRepository
func (_mock *ProductRepository) Fetch(ctx context.Context, filter request.ProductFilter) ([]entity.Product, int64, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []entity.Product
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.ProductFilter) ([]entity.Product, int64, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.ProductFilter) []entity.Product); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, request.ProductFilter) int64); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, request.ProductFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ProductRepository_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type ProductRepository_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - filter request.ProductFilter
func (_e *ProductRepository_Expecter) Fetch(ctx interface{}, filter interface{}) *ProductRepository_Fetch_Call {
	return &ProductRepository_Fetch_Call{Call: _e.mock.On("Fetch", ctx, filter)}
}

func (_c *ProductRepository_Fetch_Call) Run(run func(ctx context.Context, filter request.ProductFilter)) *ProductRepository_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 request.ProductFilter
		if args[1] != nil {
			arg1 = args[1].(request.ProductFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductRepository_Fetch_Call) Return(products []entity.Product, n int64, err error) *ProductRepository_Fetch_Call {
	_c.Call.Return(products, n, err)
	return _c
}

func (_c *ProductRepository_Fetch_Call) RunAndReturn(run func(ctx context.Context, filter request.ProductFilter) ([]entity.Product, int64, error)) *ProductRepository_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type ProductRepository
func (_mock *ProductRepository) GetByID(ctx context.Context, id int64) (*entity.Product, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*entity.Product, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *entity.Product); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ProductRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *ProductRepository_Expecter) GetByID(ctx interface{}, id interface{}) *ProductRepository_GetByID_Call {
	return &ProductRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ProductRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *ProductRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductRepository_GetByID_Call) Return(product *entity.Product, err error) *ProductRepository_GetByID_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *ProductRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*entity.Product, error)) *ProductRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
