// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"erajaya-test/internal/models/entity"
	"erajaya-test/internal/models/request"
	"erajaya-test/shared/response"

	mock "github.com/stretchr/testify/mock"
)

// NewProductUsecase creates a new instance of ProductUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductUsecase {
	mock := &ProductUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProductUsecase is an autogenerated mock type for the ProductUsecase type
type ProductUsecase struct {
	mock.Mock
}

type ProductUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductUsecase) EXPECT() *ProductUsecase_Expecter {
	return &ProductUsecase_Expecter{mock: &_m.Mock}
}

// CreateProduct provides a mock function for the type ProductUsecase
func (_mock *ProductUsecase) CreateProduct(ctx context.Context, req *request.Product) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *request.Product) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductUsecase_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type ProductUsecase_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.Product
func (_e *ProductUsecase_Expecter) CreateProduct(ctx interface{}, req interface{}) *ProductUsecase_CreateProduct_Call {
	return &ProductUsecase_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, req)}
}

func (_c *ProductUsecase_CreateProduct_Call) Run(run func(ctx context.Context, req *request.Product)) *ProductUsecase_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *request.Product
		if args[1] != nil {
			arg1 = args[1].(*request.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductUsecase_CreateProduct_Call) Return(err error) *ProductUsecase_CreateProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductUsecase_CreateProduct_Call) RunAndReturn(run func(ctx context.Context, req *request.Product) error) *ProductUsecase_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductByID provides a mock function for the type ProductUsecase
func (_mock *ProductUsecase) GetProductByID(ctx context.Context, id int64) (*entity.Product, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 *entity.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*entity.Product, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *entity.Product); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductUsecase_GetProductByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductByID'
type ProductUsecase_GetProductByID_Call struct {
	*mock.Call
}

// GetProductByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *ProductUsecase_Expecter) GetProductByID(ctx interface{}, id interface{}) *ProductUsecase_GetProductByID_Call {
	return &ProductUsecase_GetProductByID_Call{Call: _e.mock.On("GetProductByID", ctx, id)}
}

func (_c *ProductUsecase_GetProductByID_Call) Run(run func(ctx context.Context, id int64)) *ProductUsecase_GetProductByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductUsecase_GetProductByID_Call) Return(product *entity.Product, err error) *ProductUsecase_GetProductByID_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *ProductUsecase_GetProductByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*entity.Product, error)) *ProductUsecase_GetProductByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListProducts provides a mock function for the type ProductUsecase
func (_mock *ProductUsecase) ListProducts(ctx context.Context, filter request.ProductFilter) ([]entity.Product, response.StdPagination, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListProducts")
	}

	var r0 []entity.Product
	var r1 response.StdPagination
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.ProductFilter) ([]entity.Product, response.StdPagination, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.ProductFilter) []entity.Product); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, request.ProductFilter) response.StdPagination); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(response.StdPagination)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, request.ProductFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ProductUsecase_ListProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProducts'
type ProductUsecase_ListProducts_Call struct {
	*mock.Call
}

// ListProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter request.ProductFilter
func (_e *ProductUsecase_Expecter) ListProducts(ctx interface{}, filter interface{}) *ProductUsecase_ListProducts_Call {
	return &ProductUsecase_ListProducts_Call{Call: _e.mock.On("ListProducts", ctx, filter)}
}

func (_c *ProductUsecase_ListProducts_Call) Run(run func(ctx context.Context, filter request.ProductFilter)) *ProductUsecase_ListProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 request.ProductFilter
		if args[1] != nil {
			arg1 = args[1].(request.ProductFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductUsecase_ListProducts_Call) Return(products []entity.Product, stdPagination response.StdPagination, err error) *ProductUsecase_ListProducts_Call {
	_c.Call.Return(products, stdPagination, err)
	return _c
}

func (_c *ProductUsecase_ListProducts_Call) RunAndReturn(run func(ctx context.Context, filter request.ProductFilter) ([]entity.Product, response.StdPagination, error)) *ProductUsecase_ListProducts_Call {
	_c.Call.Return(run)
	return _c
}
